class Country {
  constructor(countryCode, id, name, displayName, flagCode) {
    this.index = countries.length;
    this.countryCode = countryCode;
    this.id = id;
    this.name = name;
    this.displayName = displayName;
    this.flagCode = flagCode;
    this.count = 0;
  }
}

countries = new Array();

countries.push(new Country("AF", 130, "Afghanistan", "Afghanistan", "🇦🇫"));
countries.push(new Country("AL", 198, "Albania", "Albania", "🇦🇱"));
countries.push(new Country("DZ", 220, "Algeria", "Algeria", "🇩🇿"));
countries.push(new Country("AS", 176, "American Samoa", "American Samoa", "🇦🇸"));
countries.push(new Country("AD", 224, "Andorra", "Andorra", "🇦🇩"));
countries.push(new Country("AO", 215, "Angola", "Angola", "🇦🇴"));
countries.push(new Country("AG", 229, "Antigua and Barbuda", "Antigua & Barbuda", "🇦🇬"));
countries.push(new Country("AR", 26, "Argentina", "Argentina", "🇦🇷"));
countries.push(new Country("AM", 131, "Armenia", "Armenia", "🇦🇲"));
countries.push(new Country("AW", 27, "Aruba", "Aruba", "🇦🇼"));
countries.push(new Country("AU", 28, "Australia", "Australia", "🇦🇺"));
countries.push(new Country("AT", 29, "Austria", "Austria", "🇦🇹"));
countries.push(new Country("AZ", 132, "Azerbaijan", "Azerbaijan", "🇦🇿"));
countries.push(new Country("BS", 115, "Bahamas", "Bahamas", "🇧🇸"));
countries.push(new Country("BD", 134, "Bangladesh", "Bangladesh", "🇧🇩"));
countries.push(new Country("BB", 196, "Barbados", "Barbados", "🇧🇧"));
countries.push(new Country("BY", 161, "Belarus", "Belarus", "🇧🇾"));
countries.push(new Country("BE", 30, "Belgium", "Belgium", "🇧🇪"));
countries.push(new Country("BZ", 31, "Belize", "Belize", "🇧🇿"));
countries.push(new Country("BJ", 230, "Benin", "Benin", "🇧🇯"));
countries.push(new Country("BM", 116, "Bermuda", "Bermuda", "🇧🇲"));
countries.push(new Country("BT", 206, "Bhutan", "Bhutan", "🇧🇹"));
countries.push(new Country("BO", 117, "Bolivia", "Bolivia", "🇧🇴"));
countries.push(new Country("BA", 162, "Bosnia and Herzegovina", "Bosnia & Herzegovina", "🇧🇦"));
countries.push(new Country("BW", 96, "Botswana", "Botswana", "🇧🇼"));
countries.push(new Country("BR", 118, "Brazil", "Brazil", "🇧🇷"));
countries.push(new Country("VG", 245, "British Virgin Islands", "British Virgin Islands", "🇻🇬"));
countries.push(new Country("BN", 133, "Brunei", "Brunei", "🇧🇳"));
countries.push(new Country("BG", 163, "Bulgaria", "Bulgaria", "🇧🇬"));
countries.push(new Country("BF", 226, "Burkina Faso", "Burkina Faso", "🇧🇷"));
countries.push(new Country("BI", 216, "Burundi", "Burundi", "🇧🇮"));
countries.push(new Country("KH", 135, "Cambodia", "Cambodia", "🇰🇭"));
countries.push(new Country("CM", 97, "Cameroon", "Cameroon", "🇨🇲"));
countries.push(new Country("CA", 32, "Canada", "Canada", "🇨🇦"));
countries.push(new Country("CV", 221, "Cape Verde", "Cape Verde", "🇨🇻"));
countries.push(new Country("KY", 201, "Cayman Islands", "Cayman Islands", "🇰🇾"));
countries.push(new Country("CF", 250, "Central African Republic", "Central African Republic", "🇨🇫"));
countries.push(new Country("TD", 231, "Chad", "Chad", "🇹🇩"));
countries.push(new Country("", 218, "Channel Islands", "Channel Islands", "🇯🇪🇬🇬"));
countries.push(new Country("CL", 119, "Chile", "Chile", "🇨🇱"));
countries.push(new Country("CN", 33, "China / People's Republic of China", "China", "🇨🇳"));
countries.push(new Country("CO", 34, "Colombia", "Colombia", "🇨🇴"));
countries.push(new Country("CK", 210, "Cook Islands", "Cook Islands", "🇨🇰"));
countries.push(new Country("CR", 120, "Costa Rica", "Costa Rica", "🇨🇷"));
countries.push(new Country("HR", 35, "Croatia", "Croatia", "🇭🇷"));
countries.push(new Country("CU", 36, "Cuba", "Cuba", "🇨🇺"));
countries.push(new Country("CO", 34, "Colombia", "Colombia", "🇨🇴"));
countries.push(new Country("CK", 210, "Cook Islands", "Cook Islands", "🇨🇰"));
countries.push(new Country("CR", 120, "Costa Rica", "Costa Rica", "🇨🇷"));
countries.push(new Country("HR", 35, "Croatia", "Croatia", "🇭🇷"));
countries.push(new Country("CU", 36, "Cuba", "Cuba", "🇨🇺"));
countries.push(new Country("CW", 238, "Curacao", "Curacao", "🇨🇼"));
countries.push(new Country("CY", 164, "Cyprus", "Cyprus", "🇨🇾"));
countries.push(new Country("CZ", 37, "Czech Republic", "Czech Republic", "🇨🇿"));
countries.push(new Country("CD", 189, "Democratic Republic of the Congo", "Democratic Republic of the Congo", "🇨🇩"));
countries.push(new Country("DK", 38, "Denmark", "Denmark", "🇩🇰"));
countries.push(new Country("DM", 209, "Dominica", "Dominica", "🇩🇲"));
countries.push(new Country("DO", 121, "Dominican Republic", "Dominican Republic", "🇩🇴"));
countries.push(new Country("EC", 93, "Ecuador", "Ecuador", "🇪🇨"));
countries.push(new Country("EG", 39, "Egypt", "Egypt", "🇪🇬"));
countries.push(new Country("SV", 40, "El Salvador", "El Salvador", "🇸🇻"));
countries.push(new Country("XE", 41, "England", "England", "🏴󠁧󠁢󠁥󠁮󠁧󠁿󠁧󠁢󠁥󠁮󠁧󠁿"));
countries.push(new Country("ER", 98, "Eritrea", "Eritrea", "🇪🇷"));
countries.push(new Country("EE", 42, "Estonia", "Estonia", "🇪🇪"));
countries.push(new Country("ET", 99, "Ethiopia", "Ethiopia", "🇪🇹"));
countries.push(new Country("FO", 232, "Faroe Islands", "Faroe Islands", "🇫🇴"));
countries.push(new Country("FJ", 177, "Fiji", "Fiji", "🇫🇯"));
countries.push(new Country("FI", 43, "Finland", "Finland", "🇫🇮"));
countries.push(new Country("FR", 44, "France", "France", "🇫🇷"));
countries.push(new Country("PF", 45, "French Polynesia", "French Polynesia", "🇵🇫"));
countries.push(new Country("GA", 244, "Gabon", "Gabon", "🇬🇦"));
countries.push(new Country("GM", 100, "Gambia", "Gambia", "🇬🇲"));
countries.push(new Country("GE", 137, "Georgia", "Georgia", "🇬🇪"));
countries.push(new Country("DE", 46, "Germany", "Germany", "🇩🇪"));
countries.push(new Country("GH", 101, "Ghana", "Ghana", "🇬🇭"));
countries.push(new Country("GI", 165, "Gibraltar", "Gibraltar", "🇬🇮"));
countries.push(new Country("GR", 47, "Greece", "Greece", "🇬🇷"));
countries.push(new Country("GL", 205, "Greenland", "Greenland", "🇬🇱"));
countries.push(new Country("GD", 242, "Grenada", "Grenada", "🇬🇩"));
countries.push(new Country("GU", 178, "Guam", "Guam", "🇬🇺"));
countries.push(new Country("GT", 122, "Guatemala", "Guatemala", "🇬🇹"));
countries.push(new Country("GN", 233, "Guinea", "Guinea", "🇬🇳"));
countries.push(new Country("GW", 222, "Guyana", "Guyana", "🇬🇾"));
countries.push(new Country("HT", 123, "Haiti", "Haiti", "🇭🇹"));
countries.push(new Country("HN", 49, "Honduras", "Honduras", "🇭🇳"));
countries.push(new Country("HK", 138, "Hong Kong", "Hong Kong", "🇭🇰"));
countries.push(new Country("HU", 50, "Hungary", "Hungary", "🇭🇺"));
countries.push(new Country("IS", 166, "Iceland", "Iceland", "🇮🇸"));
countries.push(new Country("IN", 51, "India", "India", "🇮🇳"));
countries.push(new Country("ID", 139, "Indonesia", "Indonesia", "🇮🇩"));
countries.push(new Country("IR", 140, "Iran", "Iran", "🇮🇷"));
countries.push(new Country("IQ", 141, "Iraq", "Iraq", "🇮🇶"));
countries.push(new Country("IE", 52, "Ireland", "Ireland", "🇮🇪"));
countries.push(new Country("IM", 195, "Isle of Man", "Isle of Man", "🇮🇲"));
countries.push(new Country("IL", 53, "Israel", "Israel", "🇮🇱"));
countries.push(new Country("IT", 54, "Italy", "Italy", "🇮🇹"));
countries.push(new Country("CI", 219, "Ivory Coast", "Ivory Coast", "🇨🇮"));
countries.push(new Country("JM", 55, "Jamaica", "Jamaica", "🇯🇲"));
countries.push(new Country("JP", 56, "Japan", "Japan", "🇯🇵"));
countries.push(new Country("JO", 142, "Jordan", "Jordan", "🇯🇴"));
countries.push(new Country("KZ", 143, "Kazakhstan", "Kazakhstan", "🇰🇿"));
countries.push(new Country("KE", 57, "Kenya", "Kenya", "🇰🇪"));
countries.push(new Country("XK", 192, "Kosovo", "Kosovo", "🇽🇰"));
countries.push(new Country("KU", 144, "Kuwait", "Kuwait", "🇰🇼"));
countries.push(new Country("KG", 211, "Kyrgyzstan", "Kyrgyzstan", "🇰🇬"));
countries.push(new Country("LA", 193, "Laos", "Laos", "🇱🇦"));
countries.push(new Country("LV", 59, "Latvia", "Latvia", "🇱🇻"));
countries.push(new Country("LB", 145, "Lebanon", "Lebanon", "🇱🇧"));
countries.push(new Country("LS", 236, "Lesotho", "Lesotho", "🇱🇸"));
countries.push(new Country("LR", 208, "Liberia", "Liberia", "🇱🇷"));
countries.push(new Country("LI", 167, "Liechtenstein", "Liechtenstein", "🇱🇮"));
countries.push(new Country("LT", 60, "Lithuania", "Lithuania", "🇱🇹"));
countries.push(new Country("LU", 168, "Luxembourg", "Luxembourg", "🇱🇺"));
countries.push(new Country("MO", 146, "Macau", "Macau", "🇲🇴"));
countries.push(new Country("MG", 217, "Madagascar", "Madagascar", "🇲🇬"));
countries.push(new Country("MW", 102, "Malawi", "Malawi", "🇲🇼"));
countries.push(new Country("MY", 147, "Malaysia", "Malaysia", "🇲🇾"));
countries.push(new Country("ML", 214, "Mali", "Mali", "🇲🇱"));
countries.push(new Country("MT", 170, "Malta", "Malta", "🇲🇹"));
countries.push(new Country("MU", 62, "Mauritius", "Mauritius", "🇲🇺"));
countries.push(new Country("MX", 63, "Mexico", "Mexico", "🇲🇽"));
countries.push(new Country("FM", 179, "Micronesia", "Micronesia", "🇫🇲"));
countries.push(new Country("MD", 171, "Moldova", "Moldova", "🇲🇩"));
countries.push(new Country("MN", 148, "Mongolia", "Mongolia", "🇲🇳"));
countries.push(new Country("ME", 172, "Montenegro", "Montenegro", "🇲🇪"));
countries.push(new Country("MA", 103, "Morocco", "Morocco", "🇲🇦"));
countries.push(new Country("MZ", 202, "Mozambique", "Mozambique", "🇲🇿"));
countries.push(new Country("MM", 223, "Myanmar (Burma)", "Myanmar (Burma)", "🇲🇲"));
countries.push(new Country("NA", 64, "Namibia", "Namibia", "🇳🇦"));
countries.push(new Country("NP", 149, "Nepal", "Nepal", "🇳🇵"));
countries.push(new Country("NL", 65, "Netherlands", "Netherlands", "🇳🇱"));
countries.push(new Country("NC", 240, "New Caledonia", "New Caledonia", "🇳🇨"));
countries.push(new Country("NZ", 67, "New Zealand", "New Zealand", "🇳🇿"));
countries.push(new Country("NI", 124, "Nicaragua", "Nicaragua", "🇳🇮"));
countries.push(new Country("NE", 105, "Niger", "Niger", "🇳🇪"));
countries.push(new Country("NG", 106, "Nigeria", "Nigeria", "🇳🇬"));
countries.push(new Country("KP", 150, "North Korea", "North Korea", "🇰🇵"));
countries.push(new Country("", 191, "Northern Ireland", "Northern Ireland", "🇬🇧"));
countries.push(new Country("MP", 180, "Northern Mariana Islands", "Northern Mariana Islands", "🇲🇵"));
countries.push(new Country("NO", 68, "Norway", "Norway", "🇳🇴"));
countries.push(new Country("OM", 151, "Oman", "Oman", "🇴🇲"));
countries.push(new Country("", 89, "Other", "Other", ""));
countries.push(new Country("PK", 152, "Pakistan", "Pakistan", "🇵🇰"));
countries.push(new Country("PW", 181, "Palau", "Palau", "🇵🇼"));
countries.push(new Country("PS", 204, "Palestinian Territories", "Palestinian Territories", "🇵🇸"));
countries.push(new Country("PA", 70, "Panama", "Panama", "🇵🇦"));
countries.push(new Country("PG", 182, "Papua New Guinea", "Papua New Guinea", "🇵🇬"));
countries.push(new Country("PY", 125, "Paraguay", "Paraguay", "🇵🇾"));
countries.push(new Country("PE", 94, "Peru", "Peru", "🇵🇪"));
countries.push(new Country("PH", 71, "Philippines", "Philippines", "🇵🇭"));
countries.push(new Country("PL", 72, "Poland", "Poland", "🇵🇱"));
countries.push(new Country("PT", 73, "Portugal", "Portugal", "🇵🇹"));
countries.push(new Country("MC", 200, "Principality of Monaco", "Principality of Monaco", "🇲🇨"));
countries.push(new Country("PR", 126, "Puerto Rico", "Puerto Rico", "🇵🇷"));
countries.push(new Country("CG", 249, "Republic of Congo", "Republic of Congo", "🇨🇬"));
countries.push(new Country("MK", 169, "Republic of Macedonia", "Republic of Macedonia", "🇲🇰"));
countries.push(new Country("RO", 173, "Romania", "Romania", "🇷🇴"));
countries.push(new Country("RU", 74, "Russia", "Russia", "🇷🇺"));
countries.push(new Country("RW", 107, "Rwanda", "Rwanda", "🇷🇼"));
countries.push(new Country("KN", 247, "Saint Kitts and Nevis", "St. Kitts & Nevis", "🇰🇳"));
countries.push(new Country("WS", 183, "Samoa", "Samoa", "🇼🇸"));
countries.push(new Country("SM", 234, "San Marino", "San Marino", "🇸🇲"));
countries.push(new Country("ST", 235, "São Tomé & Príncipe", "São Tomé & Príncipe", "🇸🇹"));
countries.push(new Country("SA", 153, "Saudi Arabia", "Saudi Arabia", "🇸🇦"));
countries.push(new Country("XS", 190, "Scotland", "Scotland", "🏴󠁧󠁢󠁳󠁣󠁴󠁿"));
countries.push(new Country("SN", 212, "Senegal", "Senegal", "🇸🇳"));
countries.push(new Country("RS", 76, "Serbia", "Serbia", "🇷🇸"));
countries.push(new Country("SC", 241, "Seychelles", "Seychelles", "🇸🇨"));
countries.push(new Country("SL", 77, "Sierra Leone", "Sierra Leone", "🇸🇱"));
countries.push(new Country("SG", 90, "Singapore", "Singapore", "🇸🇬"));
countries.push(new Country("SK", 78, "Slovakia", "Slovakia", "🇸🇰"));
countries.push(new Country("SI", 95, "Slovenia", "Slovenia", "🇸🇮"));
countries.push(new Country("SB", 184, "Solomon Islands", "Solomon Islands", "🇸🇧"));
countries.push(new Country("ZA", 108, "South Africa", "South Africa", "🇿🇦"));
countries.push(new Country("KR", 154, "South Korea", "South Korea", "🇰🇷"));
countries.push(new Country("ES", 79, "Spain", "Spain", "🇪🇸"));
countries.push(new Country("LK", 155, "Sri Lanka", "Sri Lanka", "🇱🇰"));
countries.push(new Country("LC", 199, "St. Lucia", "St. Lucia", "🇱🇨"));
countries.push(new Country("VC", 197, "St. Vincent &amp; the Grenadines", "St. Vincent & Grenadines", "🇻🇨"));
countries.push(new Country("SD", 110, "Sudan", "Sudan", "🇸🇩"));
countries.push(new Country("SR", 203, "Surinam", "Suriname", "🇸🇷"));
countries.push(new Country("SZ", 109, "Swaziland", "Swaziland", "🇸🇿"));
countries.push(new Country("SE", 80, "Sweden", "Sweden", "🇸🇪"));
countries.push(new Country("CH", 81, "Switzerland", "Switzerland", "🇨🇭"));
countries.push(new Country("SY", 225, "Syria", "Syria", "🇸🇾"));
countries.push(new Country("TW", 82, "Taiwan", "Taiwan", "🇹🇼"));
countries.push(new Country("TJ", 156, "Tajikistan", "Tajikistan", "🇹🇯"));
countries.push(new Country("TZ", 207, "Tanzania", "Tanzania", "🇹🇿"));
countries.push(new Country("TH", 83, "Thailand", "Thailand", "🇹🇭"));
countries.push(new Country("TG", 84, "Togo", "Togo", "🇹🇬"));
countries.push(new Country("TK", 186, "Tokelau", "Tokelau", "🇹🇰"));
countries.push(new Country("TO", 185, "Tonga", "Tonga", "🇹🇴"));
countries.push(new Country("TT", 127, "Trinidad and Tobago", "Trinidad & Tobago", "🇹🇹"));
countries.push(new Country("TN", 112, "Tunisia", "Tunisia", "🇹🇳"));
countries.push(new Country("TR", 157, "Turkey", "Turkey", "🇹🇷"));
countries.push(new Country("TM", 158, "Turkmenistan", "Turkmenistan", "🇹🇲"));
countries.push(new Country("TC", 243, "Turks and Caicos Islands", "Turks & Caicos Islands", "🇹🇨"));
countries.push(new Country("UG", 111, "Uganda", "Uganda", "🇺🇬"));
countries.push(new Country("UA", 175, "Ukraine", "Ukraine", "🇺🇦"));
countries.push(new Country("AE", 159, "United Arab Emirates", "United Arab Emirates", "🇦🇪"));
countries.push(new Country("US", 86, "United States", "United States", "🇺🇸"));
countries.push(new Country("VI", 128, "United States Virgin Islands", "U.S. Virgin Islands", "🇻🇮"));
countries.push(new Country("UY", 129, "Uruguay", "Uruguay", "🇺🇾"));
countries.push(new Country("UZ", 194, "Uzbekistan", "Uzbekistan", "🇺🇿"));
countries.push(new Country("VU", 187, "Vanuatu", "Vanuatu", "🇻🇺"));
countries.push(new Country("VE", 92, "Venezuela", "Venezuela", "🇻🇪"));
countries.push(new Country("VN", 87, "Vietnam", "Vietnam", "🇻🇳"));
countries.push(new Country("XW", 88, "Wales", "Wales", "🏴󠁧󠁢󠁷󠁬󠁳󠁿"));
countries.push(new Country("YE", 160, "Yemen", "Yemen", "🇾🇪"));
countries.push(new Country("ZM", 113, "Zambia", "Zambia", "🇿🇲"));
countries.push(new Country("ZW", 114, "Zimbabwe", "Zimbabwe", "🇿🇼"));
